language: php
php:
  - 7.1.1
env:
  - MYSQL_HOST=127.0.0.1 MYSQL_USER=root
services:
  - mysql

# addons:
#   apt:
#     sources:
#       - mysql-5.6-trusty
#     packages:
#      - mysql-server
# dist: trusty
sudo: required
before_install:
  - composer self-update --rollback
  - mysql -e 'CREATE DATABASE moodle;'
  - mysql -u root --password='' moodle < dbDump/dump.sql
  - mysql -e 'USE moodle;'
install:
  - composer require satooshi/php-coveralls:~0.6@stable
  - composer require --dev phpunit/dbunit
  - composer install
before_script:
  - mkdir -p ./test_reports/logs
script:
  - phpunit --version
  - composer dump-autoload
  - phpunit  --coverage-clover ./test_reports/logs/clover.xml
after_script:
- php vendor/bin/coveralls -v

after_success:
- coveralls-upload
